/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author Jojos
 */
public class Acerca_de extends javax.swing.JFrame {

    /**
     * Creates new form Acerca_de
     */
    public Acerca_de() {
        initComponents();
        this.setLocationRelativeTo(null);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        FrogSoft = new javax.swing.JLabel();
        Regresar = new javax.swing.JButton();
        PollBall = new javax.swing.JLabel();
        Texto = new javax.swing.JLabel();
        Texto1 = new javax.swing.JLabel();
        Texto2 = new javax.swing.JLabel();
        Texto3 = new javax.swing.JLabel();
        Texto4 = new javax.swing.JLabel();
        Fondo = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        FrogSoft.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/FrogSoft.png"))); // NOI18N
        getContentPane().add(FrogSoft, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 60, 170, 140));

        Regresar.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Regresar.png"))); // NOI18N
        Regresar.setContentAreaFilled(false);
        Regresar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                RegresarActionPerformed(evt);
            }
        });
        getContentPane().add(Regresar, new org.netbeans.lib.awtextra.AbsoluteConstraints(360, 440, 130, 50));

        PollBall.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/POOLBALL_LOGO.png"))); // NOI18N
        PollBall.setToolTipText("");
        getContentPane().add(PollBall, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 50, -1, 190));

        Texto.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto.setLabelFor(Texto);
        Texto.setText("Empresa: FrogSoft");
        getContentPane().add(Texto, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 250, 200, 30));

        Texto1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto1.setLabelFor(Texto);
        Texto1.setText("Numero de contacto: 5971145270 ");
        getContentPane().add(Texto1, new org.netbeans.lib.awtextra.AbsoluteConstraints(20, 330, 400, 30));

        Texto2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto2.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto2.setLabelFor(Texto);
        Texto2.setText("PollBall - WORKING PROGRESS\n");
        getContentPane().add(Texto2, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 210, 330, 30));

        Texto3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto3.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto3.setLabelFor(Texto);
        Texto3.setText("Dirección: Calle 5 de mayo, Sin numero, 9C, Tlahuelilpan Centro.");
        getContentPane().add(Texto3, new org.netbeans.lib.awtextra.AbsoluteConstraints(60, 370, 600, 30));

        Texto4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        Texto4.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        Texto4.setLabelFor(Texto);
        Texto4.setText("Contacto: FrogSoft_2023@gmail.com ");
        getContentPane().add(Texto4, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 290, 390, 30));

        Fondo.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Acerca de_Menu.png"))); // NOI18N
        getContentPane().add(Fondo, new org.netbeans.lib.awtextra.AbsoluteConstraints(-60, 0, 930, 560));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void RegresarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_RegresarActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        
    }//GEN-LAST:event_RegresarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Acerca_de.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Acerca_de.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Acerca_de.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Acerca_de.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Acerca_de().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel Fondo;
    private javax.swing.JLabel FrogSoft;
    private javax.swing.JLabel PollBall;
    private javax.swing.JButton Regresar;
    private javax.swing.JLabel Texto;
    private javax.swing.JLabel Texto1;
    private javax.swing.JLabel Texto2;
    private javax.swing.JLabel Texto3;
    private javax.swing.JLabel Texto4;
    // End of variables declaration//GEN-END:variables
}
