/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

//import java.awt.Graphics;
//import java.awt.Image;
//import javax.swing.ImageIcon;
//import javax.swing.JPanel;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author eduarckangrck
 */
public class ajustes extends javax.swing.JFrame {

   // DefaultTableModel dtm = new DefaultTableModel();
    

    /**
     * Creates new form ajustes
     */
    public ajustes() {
        initComponents();
        setLocationRelativeTo(null);
        String[] titulo = new String[]{"id", "Precio", "Producto"};
       // dtm.setColumnIdentifiers(titulo);
        //tbDatos.setModel(dtm);
    }

   /* void agregar() {
        dtm.addRow(new Object[]{
            txtId.getText(), txtPres.getText(), txtProd.getText()
        });
  mesa1 mes = new mesa1();
        mes.agree(txtProd.getText());
    }

    void eliminar() {
        int fila = tbDatos.getSelectedRow();
        dtm.removeRow(fila);

    }

    void actualizar() {
        int fila = tbDatos.getSelectedRow();
        dtm.setValueAt(txtId.getText(), fila, 0);
        dtm.setValueAt(txtPres.getText(), fila, 1);
        dtm.setValueAt(txtProd.getText(), fila, 2);
        
    }

    void limpiar() {
        int filas = dtm.getRowCount();
        for (int i = 0; i < filas; i++) {
            dtm.removeRow(0);

        }
    }*/

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        r = new javax.swing.JTextField();
        s = new javax.swing.JTextField();
        j = new javax.swing.JTextField();
        pa = new javax.swing.JTextField();
        c = new javax.swing.JTextField();
        p = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField7 = new javax.swing.JTextField();
        jLabel3 = new javax.swing.JLabel();
        jPasswordField1 = new javax.swing.JPasswordField();
        jButton2 = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        h = new javax.swing.JTextField();
        jLabel_fond = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setUndecorated(true);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Regresar.png"))); // NOI18N
        jButton1.setToolTipText("Regresar a la ventana anterior");
        jButton1.setBorder(null);
        jButton1.setBorderPainted(false);
        jButton1.setContentAreaFilled(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 50, 150, 80));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("SOPA INSTANTANEA:");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 230, 210, 20));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("JUGOS:");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 270, 80, 20));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("PALOMITAS:");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(560, 310, 130, -1));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("CERVESA:");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 350, 100, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("REFRESCO:");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(570, 200, 120, 20));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Hot Dog :");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 390, 110, -1));

        r.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        r.setText("30");
        getContentPane().add(r, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 190, 120, -1));

        s.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        s.setText("30");
        getContentPane().add(s, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 230, 120, -1));

        j.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        j.setText("30");
        getContentPane().add(j, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 270, 120, -1));

        pa.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        pa.setText("30");
        getContentPane().add(pa, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 310, 120, -1));

        c.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        c.setText("30");
        getContentPane().add(c, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 350, 120, -1));

        p.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        p.setText("30");
        getContentPane().add(p, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 150, 120, -1));

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("PRODUCTOS");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 100, 120, 30));

        jLabel2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel2.setText("Usuario :");
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 200, 90, 40));

        jTextField7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jTextField7.setText("admin");
        getContentPane().add(jTextField7, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 210, 110, -1));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Contraseña :");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 270, -1, -1));

        jPasswordField1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jPasswordField1.setText("12345");
        getContentPane().add(jPasswordField1, new org.netbeans.lib.awtextra.AbsoluteConstraints(200, 270, 130, 40));

        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("Actualizar");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2, new org.netbeans.lib.awtextra.AbsoluteConstraints(670, 430, 140, 40));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("PAPAS:");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 150, 110, -1));

        h.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        h.setText("30");
        getContentPane().add(h, new org.netbeans.lib.awtextra.AbsoluteConstraints(680, 390, 120, 30));

        jLabel_fond.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/Mesa_principal.png"))); // NOI18N
        getContentPane().add(jLabel_fond, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 1050, 590));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
    this.setVisible(false );        // TODO add your handling code here:
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
      mesa1 mes = new mesa1();
        mes.setP(p.getText());
        mes.setH(h.getText());
        mes.setPa(pa.getText());
        mes.setJ(j.getText());
        mes.setR(r.getText());
        mes.setC(c.getText());
        mes.setS(s.getText());

        // TODO add your handling code here:
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ajustes.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ajustes().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField c;
    private javax.swing.JTextField h;
    private javax.swing.JTextField j;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JLabel jLabel_fond;
    private javax.swing.JPasswordField jPasswordField1;
    private javax.swing.JTextField jTextField7;
    private javax.swing.JTextField p;
    private javax.swing.JTextField pa;
    private javax.swing.JTextField r;
    private javax.swing.JTextField s;
    // End of variables declaration//GEN-END:variables

   /* public void val(String num) {

        if (num.length() > 0 && num.length() < 8) {

            for (int i = 0; i < num.length(); i++) {
                char c = num.charAt(i);
                if (!Character.isDigit(c)) {
                    txtId.setText("0");

                }

            }

        } else {
            txtId.setText("0");
        }

    }

    public void valPres(String num) {

        if (num.length() > 0 && num.length() < 8) {

            for (int i = 0; i < num.length(); i++) {
                char c = num.charAt(i);
                if (Character.isDigit(c) || c == '.') {
                    txtPres.setText(num);

                } else {
                    txtPres.setText("0");
                }

            }

        } else {
            txtPres.setText("0");
        }

    }*/
}
