/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Vistas;

/**
 *
 * @author eduarckangrck
 */
public class Pool_Menu extends javax.swing.JFrame {

    /**
     * Creates new form Pool_Menu
     */
    public Pool_Menu() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel17 = new javax.swing.JLabel();
        jLabel18 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jLabel19 = new javax.swing.JLabel();
        jLabel20 = new javax.swing.JLabel();
        mes5 = new javax.swing.JButton();
        mes1 = new javax.swing.JButton();
        mes2 = new javax.swing.JButton();
        m4 = new javax.swing.JButton();
        m3 = new javax.swing.JButton();
        mes3 = new javax.swing.JButton();
        mes6 = new javax.swing.JButton();
        mes7 = new javax.swing.JButton();
        mes8 = new javax.swing.JButton();
        m5 = new javax.swing.JButton();
        m6 = new javax.swing.JButton();
        m7 = new javax.swing.JButton();
        m8 = new javax.swing.JButton();
        m9 = new javax.swing.JButton();
        m10 = new javax.swing.JButton();
        mes10 = new javax.swing.JButton();
        m11 = new javax.swing.JButton();
        mes9 = new javax.swing.JButton();
        WALL1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel1.setText("Mesa 2");
        getContentPane().add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 100, 80, 30));

        jLabel4.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel4.setText("Mesa3");
        getContentPane().add(jLabel4, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 100, 80, 30));

        jLabel3.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel3.setText("Mesa4");
        getContentPane().add(jLabel3, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 90, 80, 30));

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/00.jpeg"))); // NOI18N
        jLabel2.setPreferredSize(new java.awt.Dimension(297, 273));
        getContentPane().add(jLabel2, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 50, 217, 168));

        jLabel5.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel5.setText("Mesa 5");
        getContentPane().add(jLabel5, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 210, 80, 30));

        jLabel6.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel6.setText("Mesa 6");
        getContentPane().add(jLabel6, new org.netbeans.lib.awtextra.AbsoluteConstraints(480, 210, 80, 30));

        jLabel7.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel7.setText("Mesa 7");
        getContentPane().add(jLabel7, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 210, 80, 30));

        jLabel8.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel8.setText("Mesa 8");
        getContentPane().add(jLabel8, new org.netbeans.lib.awtextra.AbsoluteConstraints(830, 210, 80, 30));

        jLabel9.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel9.setText("Mesa 9");
        getContentPane().add(jLabel9, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 320, 80, 30));

        jLabel10.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel10.setText("Mesa 10");
        getContentPane().add(jLabel10, new org.netbeans.lib.awtextra.AbsoluteConstraints(490, 310, 80, 30));

        jLabel11.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel11.setText("Mesa 11");
        getContentPane().add(jLabel11, new org.netbeans.lib.awtextra.AbsoluteConstraints(660, 310, 80, 30));

        jLabel12.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel12.setText("Mesa 12");
        getContentPane().add(jLabel12, new org.netbeans.lib.awtextra.AbsoluteConstraints(820, 310, 80, 30));

        jLabel13.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel13.setText("Mesa 13");
        getContentPane().add(jLabel13, new org.netbeans.lib.awtextra.AbsoluteConstraints(300, 430, 80, 30));

        jLabel14.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel14.setText("Mesa 14");
        getContentPane().add(jLabel14, new org.netbeans.lib.awtextra.AbsoluteConstraints(470, 430, 80, 30));

        jLabel17.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel17.setText("AJUSTES ");
        getContentPane().add(jLabel17, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 240, 90, 30));

        jLabel18.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel18.setText("AYUDA ");
        getContentPane().add(jLabel18, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 330, 80, 30));

        jLabel16.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel16.setText("Mesa 1");
        getContentPane().add(jLabel16, new org.netbeans.lib.awtextra.AbsoluteConstraints(310, 100, 80, 30));

        jLabel19.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel19.setText("ACERCA DE ");
        getContentPane().add(jLabel19, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 430, 120, 30));

        jLabel20.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jLabel20.setText("Mesa 15");
        getContentPane().add(jLabel20, new org.netbeans.lib.awtextra.AbsoluteConstraints(640, 430, 80, 30));

        mes5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m1.jpeg"))); // NOI18N
        mes5.setBorder(null);
        mes5.setBorderPainted(false);
        mes5.setContentAreaFilled(false);
        mes5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes5ActionPerformed(evt);
            }
        });
        getContentPane().add(mes5, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 220, -1, 80));

        mes1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m1.jpeg"))); // NOI18N
        mes1.setBorder(null);
        mes1.setBorderPainted(false);
        mes1.setContentAreaFilled(false);
        mes1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes1ActionPerformed(evt);
            }
        });
        getContentPane().add(mes1, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 190, -1, 80));

        mes2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m2.jpeg"))); // NOI18N
        mes2.setBorder(null);
        mes2.setBorderPainted(false);
        mes2.setContentAreaFilled(false);
        getContentPane().add(mes2, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 180, 160, 90));

        m4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m4.jpeg"))); // NOI18N
        m4.setBorder(null);
        m4.setBorderPainted(false);
        m4.setContentAreaFilled(false);
        getContentPane().add(m4, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 310, 160, 80));

        m3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m3.jpeg"))); // NOI18N
        m3.setBorder(null);
        m3.setBorderPainted(false);
        m3.setContentAreaFilled(false);
        getContentPane().add(m3, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 180, 170, 90));

        mes3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m1.jpeg"))); // NOI18N
        mes3.setBorder(null);
        mes3.setBorderPainted(false);
        mes3.setContentAreaFilled(false);
        mes3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes3ActionPerformed(evt);
            }
        });
        getContentPane().add(mes3, new org.netbeans.lib.awtextra.AbsoluteConstraints(610, 290, -1, 80));

        mes6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m2.jpeg"))); // NOI18N
        mes6.setBorder(null);
        mes6.setBorderPainted(false);
        mes6.setContentAreaFilled(false);
        getContentPane().add(mes6, new org.netbeans.lib.awtextra.AbsoluteConstraints(70, 400, 160, 90));

        mes7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m2.jpeg"))); // NOI18N
        mes7.setBorder(null);
        mes7.setBorderPainted(false);
        mes7.setContentAreaFilled(false);
        getContentPane().add(mes7, new org.netbeans.lib.awtextra.AbsoluteConstraints(780, 280, 160, 90));

        mes8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m2.jpeg"))); // NOI18N
        mes8.setBorder(null);
        mes8.setBorderPainted(false);
        mes8.setContentAreaFilled(false);
        getContentPane().add(mes8, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 70, 160, 90));

        m5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m4.jpeg"))); // NOI18N
        m5.setBorder(null);
        m5.setBorderPainted(false);
        m5.setContentAreaFilled(false);
        getContentPane().add(m5, new org.netbeans.lib.awtextra.AbsoluteConstraints(440, 290, 160, 80));

        m6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m4.jpeg"))); // NOI18N
        m6.setBorder(null);
        m6.setBorderPainted(false);
        m6.setContentAreaFilled(false);
        getContentPane().add(m6, new org.netbeans.lib.awtextra.AbsoluteConstraints(600, 410, 160, 80));

        m7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m4.jpeg"))); // NOI18N
        m7.setBorder(null);
        m7.setBorderPainted(false);
        m7.setContentAreaFilled(false);
        getContentPane().add(m7, new org.netbeans.lib.awtextra.AbsoluteConstraints(770, 70, 160, 80));

        m8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m3.jpeg"))); // NOI18N
        m8.setBorder(null);
        m8.setBorderPainted(false);
        m8.setContentAreaFilled(false);
        getContentPane().add(m8, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 400, 170, 90));

        m9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m3.jpeg"))); // NOI18N
        m9.setBorder(null);
        m9.setBorderPainted(false);
        m9.setContentAreaFilled(false);
        getContentPane().add(m9, new org.netbeans.lib.awtextra.AbsoluteConstraints(430, 400, 170, 90));

        m10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m3.jpeg"))); // NOI18N
        m10.setBorder(null);
        m10.setBorderPainted(false);
        m10.setContentAreaFilled(false);
        getContentPane().add(m10, new org.netbeans.lib.awtextra.AbsoluteConstraints(590, 70, 170, 90));

        mes10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m1.jpeg"))); // NOI18N
        mes10.setBorder(null);
        mes10.setBorderPainted(false);
        mes10.setContentAreaFilled(false);
        mes10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                mes10ActionPerformed(evt);
            }
        });
        getContentPane().add(mes10, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 80, -1, 80));

        m11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m4.jpeg"))); // NOI18N
        m11.setBorder(null);
        m11.setBorderPainted(false);
        m11.setContentAreaFilled(false);
        getContentPane().add(m11, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 190, 160, 80));

        mes9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/m2.jpeg"))); // NOI18N
        mes9.setBorder(null);
        mes9.setBorderPainted(false);
        mes9.setContentAreaFilled(false);
        getContentPane().add(mes9, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 290, 160, 90));

        WALL1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/pol0.jpeg"))); // NOI18N
        getContentPane().add(WALL1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, -10, 1000, 600));

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void mes1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mes1ActionPerformed

    private void mes3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mes3ActionPerformed

    private void mes5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mes5ActionPerformed

    private void mes10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_mes10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_mes10ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Pool_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Pool_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Pool_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Pool_Menu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Pool_Menu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel WALL1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel18;
    private javax.swing.JLabel jLabel19;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel20;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JButton m10;
    private javax.swing.JButton m11;
    private javax.swing.JButton m3;
    private javax.swing.JButton m4;
    private javax.swing.JButton m5;
    private javax.swing.JButton m6;
    private javax.swing.JButton m7;
    private javax.swing.JButton m8;
    private javax.swing.JButton m9;
    private javax.swing.JButton mes1;
    private javax.swing.JButton mes10;
    private javax.swing.JButton mes2;
    private javax.swing.JButton mes3;
    private javax.swing.JButton mes5;
    private javax.swing.JButton mes6;
    private javax.swing.JButton mes7;
    private javax.swing.JButton mes8;
    private javax.swing.JButton mes9;
    // End of variables declaration//GEN-END:variables
}
